# Generated by Django 5.2 on 2025-05-31 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
